export const CHARACTERLIST = "CHARACTERLIST";

export const CHARACTERDETAIL = "CHARACTERDETAIL";

export const EPISODENAME = "EPISODENAME";

export const CLEARLIST = "CLEARLIST";

export const CLEARDETAIL = "CLEARDETAIL";


